### ISSUE TITLE
Feature request: multiple links per manga

### ISSUE THREAD

**Issue by schklom** [diogovalentte/mantium#3]
I don't think it is currently possible to have multiple source links per manga.

A new chapter might be available on e.g. Mangahub before Mangadex, and it would be nice to know that a new chapter is available on another website.

**Comment by diogovalentte** [comment]
Currently, you can add the same manga from multiple sources. They'll be treated as different manga, and show in the dashboard as different manga on their own cards, like in the image below. You'll also receive a notification for each manga when a new chapter is released. Is this what you want?

![image](https://github.com/user-attachments/assets/947cd396-4ed4-4043-84c1-376852dffce2)

**Comment by schklom** [comment]
Yes, but these count as separate mangas with separate "Last read chapter" and "Last release chapter" entries. My idea was to combine them in a single one. That way, if any source releases a new chapter, I don't have to remember if that chapter has already been released by another source and if I already read it.

**Comment by diogovalentte** [comment]
I'm having a hard time thinking about how would that work in practice.

How the user and Mantium should combine the mangas? For example, the user would need to add a manga from mangadex, then click to highlight the manga and add the same manga from comick manually by searching it by name or providing the manga URL from comick. Is this the workflow you had in mind?

Also:
- The metadata like manga name and cover should be obtained from which source? Should the "original" source be used for this (mangadex in this example)?
- When the user clicks to select the last read chapter, Mantium should show the list of chapters from the mangadex source or the comick source?

I need a more detailed explanation of how it would work.

**Comment by schklom** [comment]
> the user would need to add a manga from mangadex, then click to highlight the manga and add the same manga from comick manually by searching it by name or providing the manga URL from comick

Exactly :)

> The metadata like manga name and cover should be obtained from which source? Should the "original" source be used for this (mangadex in this example)?

I guess the metadata can be obtained from the first link (original source), it wouldn't matter much (at least to me). Or maybe just the first link in a list of links, and let the user manage that list?

> When the user clicks to select the last read chapter, Mantium should show the list of chapters from the mangadex source or the comick source?

That would be great! Sometimes, Comick puts the chapter behind a timer, and sometimes a website's server is down. This would let a user easily pick another link that works.

**Comment by diogovalentte** [comment]
Ok, I'll think more about it throughout the week. I usually work on Mantium on weekends only, so if I get it all sorted, I can work on it next weekend.

**Comment by diogovalentte** [comment]
@schklom I added the feature and named it "multimanga". I created a [doc explaining it](https://github.com/diogovalentte/mantium/blob/main/multimangas.md), can you read it and watch the demo video to give me your opinion? If there's anything that you didn't understand or want me to edit the doc, feel free to comment.

When you give me a yes, I'll properly release the new version and docker images with this new feature.

**Comment by diogovalentte** [comment]
Closing this as the feature was implemented in version 2.0, and lack of feedback.

**Comment by schklom** [comment]
Sorry for the lack of reply.
It is pretty much exactly what I wanted, thank you very much :)

Some small improvement idea: why not treat by default all mangas as multimangas? It doesn't seem there is a downside to it, and the user wouldn't have to spend 10 seconds per manga to add that characteristic.

**Comment by diogovalentte** [comment]
Treating all mangas as multimangas is a good idea. I released [version 3.0.0](https://github.com/diogovalentte/mantium/releases/tag/v3.0.0) and now all mangas are multimangas.
