### ISSUE TITLE
Mantium-api container immediately exits

### ISSUE THREAD

**Issue by anarion80** [diogovalentte/mantium#4]
Last week my [tests for Ansible-NAS](https://github.com/anarion80/ansible-nas/actions/runs/11084587425) failed on Mantium.

After checking in more detail, looks like Mantium-api container exits immediately after creation with the following error:

```go
panic: error umarshaling configs from file './configs/configs.json': invalid character '"' after object key:value pair
goroutine 1 [running]:
main.init.0()
	/app/api/main.go:34 +0x205
```

This is with empty `/configs` directory bind mounted to the container at `/app/api/configs` like in the provided docker-compose.

**Comment by diogovalentte** [comment]
I released a new image, can you test it and give me feedback?

**Comment by anarion80** [comment]
Yes, it works now, thanks.
